image: ruby:2.3

variables:
    JEKYLL_ENV: production
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - apt-get -qq update && apt-get -qq install -y tor netcat-openbsd openssh-server openssh-client
    - /etc/init.d/tor start
    - mkdir -p ~/.ssh && touch ~/.ssh/config
    - echo "$PRIVATE_KEY" > ~/.ssh/deploy_key
    - touch ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/deploy_key
    - echo "Unset DISPLAY and SSH_ASKPASS variable" && unset DISPLAY && unset SSH_ASKPASS
    - echo "StrictHostKeyChecking=no" >> ~/.ssh/config
    - echo "Host *.onion" >> ~/.ssh/config
    - echo "    ProxyCommand /usr/bin/nc -x localhost:9050 %h %p" >> ~/.ssh/config
    - eval $(ssh-agent)
    - echo "Add deploy key to keychain" && ssh-add ~/.ssh/deploy_key
    - echo "Wait 10 seconds to bootstrap" && sleep 10
    - git submodule sync --recursive
    - git submodule foreach git pull origin master
    - echo "Build to _site" && rake deploy

pages:
    stage: deploy
    script:
    - bundle exec jekyll build -d public
    - echo "Making deploy to nlboxqa32a4mja67wgnowska7gsnhyonu6dzry3whd6cba277hkbmcid.onion" && cd _site/ && scp -o "ProxyCommand nc -x localhost:9050 %h %p" -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -r * deploy@2ma67qeyulhuw4xl.onion:/www-onions
    artifacts:
        paths:
        - public
    only:
    - master
